### ISSUE TITLE
询问有关LUGWIKI账户注册与密码重置的问题

### ISSUE THREAD

**Issue by bobby285271** [ustclug/lugwiki#4]
![screenshot_2017-01-17-15-38-53-173_com ucmobile](https://cloud.githubusercontent.com/assets/20080233/22012155/a8462f5e-dccd-11e6-8d87-ba789367c576.png)
由于记性不好，试图注册时发现用户名已存在，但因忘记密码，试图重置密码时发现无法发送邮件。
![screenshot_2017-01-17-15-39-50-296_com ucmobile](https://cloud.githubusercontent.com/assets/20080233/22012217/f1f437ae-dccd-11e6-832b-88e215e457b5.png)
欲重新注册另一账户发现类似的情况。
![screenshot_2017-01-17-15-53-13-860_com ucmobile](https://cloud.githubusercontent.com/assets/20080233/22012393/bdb667ea-dcce-11e6-9d51-a1cb76f1d853.png)

请问各位:
LUGWIKI是否为开放注册?如果是，我的账号（用户名为bobby285271）是否的确存在?若存在，是否有找回密码的方法?

**Comment by ustcjerry** [comment]
遇到同样的问题，不管是注册新用户还是找回原来的密码，都会显示：
![qq 20170301111609](https://cloud.githubusercontent.com/assets/11849381/23444504/89b45ce0-fe70-11e6-8462-aeaacfc90cb5.jpg)

**Comment by gaoyifan** [comment]
已修复
